language: python
python:
    - "2.7"
    - "3.5"
before_install:
- openssl aes-256-cbc -k $encryption_token -in apikey.py.enc -out goodreads/apikey.py -d
install:
- pip install -r requirements.txt
- pip install coveralls
script: nosetests --with-coverage --cover-package=goodreads
notifications:
  email: false
after_success:
  coveralls
